name: flutter_event_calendar_example
description: Example for Flutter Event Calendar package

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  flutter_event_calendar:
    path: ../
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_svg: ^1.1.4
  get_it: ^7.2.0
  flutter_colorpicker: ^1.0.3
  equatable: ^2.0.5
  get_storage: ^2.0.3
  expandable: ^5.0.1
  widget_with_codeview: ^2.0.1+2
  hive: ^2.2.3
  flutter_syntax_view: ^4.0.0
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Dancing
      fonts:
        - asset: assets/fonts/DancingScript_VariableFont_wght.ttf

    - family: IRanSans
      fonts:
       - asset: assets/fonts/IRANSansMobile_Black.ttf
  assets:
  - assets/
 
    
  uses-material-design: true
